
window.data = [];

data = {

info:
  [
    {
      "start": 2,
      "weight": 0.92,
      "cat0": null,
      "cat1": 3,
      "cat2": 3,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 0,
      "weight": 1,
      "cat0": null,
      "cat1": 2,
      "cat2": 3,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": 2,
      "slide": 1,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 4,
      "weight": 0.84,
      "cat0": null,
      "cat1": 3,
      "cat2": 2,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 18,
      "weight": 0.28,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": 1,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 3,
      "weight": 0.88,
      "cat0": 1,
      "cat1": 1,
      "cat2": 2,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": 1,
      "cat7": null,
      "cat8": 1,
      "subcat": 6,
      "slide": 2,
      "subcat2": 0,
      "slide2": 1
    },
    {
      "start": 15,
      "weight": 0.4,
      "cat0": 3,
      "cat1": 1,
      "cat2": null,
      "cat3": null,
      "cat4": 1,
      "cat5": 2,
      "cat6": 3,
      "cat7": null,
      "cat8": 1,
      "subcat": 0,
      "slide": 1,
      "subcat2": 5,
      "slide2": 1
    },
    {
      "start": 12,
      "weight": 0.52,
      "cat0": 3,
      "cat1": 1,
      "cat2": null,
      "cat3": null,
      "cat4": 1,
      "cat5": null,
      "cat6": 3,
      "cat7": null,
      "cat8": 1,
      "subcat": 0,
      "slide": 1,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 16,
      "weight": 0.36,
      "cat0": null,
      "cat1": 1,
      "cat2": 1,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 6,
      "weight": 0.76,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": 3,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 9,
      "weight": 0.64,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": null,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 1,
      "weight": 0.96,
      "cat0": 1,
      "cat1": 1,
      "cat2": null,
      "cat3": null,
      "cat4": 3,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": 0,
      "slide": 2,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 10,
      "weight": 0.6,
      "cat0": null,
      "cat1": 1,
      "cat2": null,
      "cat3": 1,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": 2,
      "cat8": 1,
      "subcat": 3,
      "slide": 2,
      "subcat2": 7,
      "slide2": 1
    },
    {
      "start": 11,
      "weight": 0.56,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": 2,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": 3,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 13,
      "weight": 0.48,
      "cat0": 2,
      "cat1": null,
      "cat2": null,
      "cat3": 1,
      "cat4": 1,
      "cat5": null,
      "cat6": null,
      "cat7": 3,
      "cat8": 1,
      "subcat": 0,
      "slide": 1,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 7,
      "weight": 0.72,
      "cat0": null,
      "cat1": 1,
      "cat2": null,
      "cat3": null,
      "cat4": 2,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 20,
      "weight": 0.19999999999999996,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": 2,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 17,
      "weight": 0.31999999999999995,
      "cat0": null,
      "cat1": null,
      "cat2": 3,
      "cat3": null,
      "cat4": null,
      "cat5": 3,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 5,
      "weight": 0.8,
      "cat0": null,
      "cat1": 2,
      "cat2": 2,
      "cat3": null,
      "cat4": null,
      "cat5": 2,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 21,
      "weight": 0.16000000000000003,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": 1,
      "cat5": null,
      "cat6": 1,
      "cat7": null,
      "cat8": null,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 19,
      "weight": 0.24,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": null,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 14,
      "weight": 0.43999999999999995,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": 2,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": 2,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 8,
      "weight": 0.6799999999999999,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": 3,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 22,
      "weight": 0.12,
      "cat0": null,
      "cat1": 1,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": 1,
      "cat8": 1,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 23,
      "weight": 0.07999999999999996,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": null,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 24,
      "weight": 0.040000000000000036,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": null,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    },
    {
      "start": 25,
      "weight": 0,
      "cat0": null,
      "cat1": null,
      "cat2": null,
      "cat3": null,
      "cat4": null,
      "cat5": null,
      "cat6": null,
      "cat7": null,
      "cat8": null,
      "subcat": null,
      "slide": null,
      "subcat2": null,
      "slide2": null
    }
  ]
}





